name: Build Kernel
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev
      - name: Build Kernel
        run: |
          git clone --depth 1 https://github.com/torvalds/linux.git
          cd linux
          cp ../.config .config
          make olddefconfig
          make -j$(nproc)
      - name: Upload Kernel
        uses: actions/upload-artifact@v3
        with:
          name: kernel-binary
          path: arch/x86/boot/bzImage
